[package]
name = "wasmtime-zephyr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ['staticlib']

[dependencies.wasmtime]
git = 'https://github.com/bytecodealliance/wasmtime'
branch = 'release-21.0.0'
default-features = false
features = ['runtime', 'component-model']
